name: Deploy the Flask app

on:
    workflow_run:
        workflows: [Docker-build-push]
        types:
            - completed
            

jobs:
    deploy:
        env: 
            DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
        runs-on: self-hosted

        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - name: deploy with docker compose
              run: docker compose up -d --build
    
    on-failure:
        runs-on: self-hosted
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
          - run: echo 'The triggering workflow failed'
