name: Python Lint

on:
    push:
        branches: [main]

jobs:
    validate:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            max-parallel: 2
            matrix:
                python-versions: ["3.9","3.10","3.11","3.12","3.13"]
        steps:
        - name: checkout code
          uses: actions/checkout@v6

        - name: setup python ${{ matrix.python-versions }}
          uses: actions/setup-python@v6
          with:
                python-version: ${{ matrix.python-versions }}

        - name: Install python dependencies
          run: pip install -r requirements.txt
          shell: bash

        - name: Run linter
          run: pylint app.py